language: php

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.4.*

    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*

    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*

    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*

before_script:
  - composer install

script:
  - phpunit
