language: php

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    # test 2.8 LTS
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    # test the latest stable 3.x release
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
    # test the latest release (including beta releases)
    - php: 7.1
      env: DEPENDENCIES=beta
    - php: 7.2

before_script:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - composer install

script:
  - phpunit
